---
title: "Test data"
format: html
---

## Name and affiliation of person filling out this form

Carissa Gervasi, carissa.gervasi@noaa.gov, SEFSC

## Primary Contact

Carissa Gervasi

## Secondary Contact

_No response_

## Indicator Name (as listed in the ESR report)

Not yet linked to an indicator

## Category (Which group is this indicator associated with?)

Not yet linked to an indicator

## Family (Which group is this indicator associated with?)

Not yet linked to an indicator

## Data Description

Ex: The data presented here are the degree heating weeks (DHW) for Puerto Rico and the US Virgin Islands Daily 5km Regional Virtual Stations.

## Data Type

Non-automated data access

## Public Availability

Source data are NOT publicly available.

## Accessibility and Constraints

Call 867-5309

## Methods for accessing and preparing data

Call the phone number, get an email with the data.

## Name of R script used to access and manipulate dataset

Test_data.R

## Key figures

Time series (standardized monthly anomaly)

## Interpretation

It's hard to interpret data that isn't real.

## Spatial Scale

County level

## Temporal Scale

Annual

## Data Limitations

The data does not exist

## Define Variables

| Name | Definition | Units |
|------|------------|-------|
| column1 | a measure of something | meters |
| column 2 | a measure of something else | numbers (thousands) |

## Key references

Ex. Surface North Atlantic MOM5-TOPAZ outputs derived from a regular hindcast and a robust diagnostic simulation experiment from 1980-01-01 to 2017-12-31 (NCEI Accession 0283628). NOAA National Centers for Environmental Information. Dataset. https://www.ncei.noaa.gov/archive/accession/0283628. Accessed 2023-02-19.

## Data Contributors

Carissa Gervasi, Mandy Karnauskas.

