---
title: Research recommendations
---

## Risks to meeting management objectives

A number of stressors were identified throughout the conceptual modeling stage (Seara) and indicator vetting process; however, consistent monitoring efforts are lacking with which to capture some of these potential impacts. For example, marine debris was identified as a major concern, but we could not find any databases reporting standardized long-term trends in marine debris. Point source pollution, derelict vessels, and other impacts to water quality are also concerns that are not well documented in quantitative terms. Coastal development, beach erosion and  their impacts on habitat loss were also a concern, particularly with respect to nursery habitats such as mangroves and seagrasses. The NOAA Office for Coastal Management's Coastal Change Analysis Program is currently in the process of updating its remotely-sensed imagery of land cover for the U.S. Caribbean; this data set will allow quantification of habitat and land use changes and can be included in future iterations of the report.    

## Fishery-dependent and fishery-independent data sources

Many of the indicators in this report are based on the self-reported logbook data known as the Caribbean Commercial Logbook (CCL). Logbook reporting began in 1974; however, reporting forms have changed throughout the years and catches have been reported at different taxonomic resolution, typically at family levels in the earlier years and at the species level only in the last decade. This makes it challenging to disentangle true signals in the indicators from changing fishing behavior from artifacts due to changes in reporting. The recent addition of an electronic reporting option in Puerto Rico is potentially particularly problematic, as the number of species being reported in the e-reporting has decreased dramatically relative to paper logbook reporting, likely due to fatigue in repeating reporting steps for each new species caught. Further work needs to be conducted to understand how the various changes in reporting forms have affected landings reports, and the influence of these reporting artifacts on the trends represented by indicators.

Additionally, there is high uncertainty surrounding some of the landings estimates, and underreporting is suspected. A significant decline in commercial landings occurred in many species around 2010, aligned with the period when many annual catch limits were initially put into place in the U.S. Caribbean, and it is thought that reporting may have been reduced in response to the catch limits out of concern that further restrictions might be put into place. In Puerto Rico, expansion factors are used and were applied to the indicators in this report, to account for known underestimates of commercial landings based on the incoming reports. These expansion factors, however, are not intended to correct for the absence of reporting across the island. Because of the issues and potential biases surrounding the self-reported commercial landings data, some of the indicators may not accurately reflect true changes in the fisheries. The indicators based on ratios or percentages (e.g., pelagic to demersal ratio, percentage of trips using a certain gear type) will be less subject to biases related to underreporting, assuming that the trips that are reported are representative of the overall fishery. There is currently no regular reporting system for recreational landings, and this also remains a major source of uncertainty in the total landings estimates.  

Due to the inherent uncertainties and potential biases in self-reported landings data, interpretation of fishery-dependent data is facilitated by comparison of trends from standardized fishery-independent data sources. The Puerto Rico Long-Term Coral Reef Monitoring Program (PRCRMP) and the USVI Territorial Coral Reef Monitoring Program (TCRMP) have conducted annual surveys of fish and benthic organisms since the late 1990s, providing a relatively long-term data set with which to analyze trends. However, these surveys are conducted at fixed sites at known locations with good habitat conditions, so may not be representative of wider regional trends in the populations. The National Coral Reef Monitoring Program (NCRMP), on the other hand, employs a stratified random sampling design, which better accounts for the variety of habitat types in the region; however, sampling is conducted every other year. Some preliminary explorations of these data sets were explored in this report, but could be mined for more signals. In particular, community-level and/or length-based indicators could be informative for understanding the response of populations and fish communities to fishing and other drivers.

## Human dimensions

From the perspective of human well-being as it relates to marine resource management, there remain gaps in understanding human dimensions and resilience to disturbances. Indicators alone may not fully capture the nuanced knowledge about habitats, seasonal patterns and fish behavior that are critical for fisherfolk and important in planning; local ecological knowledge has proven helpful for filling these gaps [see @garcía-quijano2007; @garcía-quijano2023]. Indicators or information on social cohesion and community identity are important in highlighting the importance of fishing for local communities in ways that goes beyond monetary benefits and speaks to the cultural significance [@valdes-pizzini2020; @griffith2007]. Fisherfolk in the U.S. Caribbean region engage in multiple occupations as a way to increase their resilience in times of crisis [@garcía-quijano2023; @yandle2020], and capturing the multiple economic activities in fishing communities would provide a more nuanced understanding of the economic diversity and vulnerability in fishing communities in the U.S. Caribbean region. Finally, indicators alone do not address the systemic barriers in accessing fishing governance [@grace-mccaskey2012; @valdés-pizzini1990].
