---
title: Integrated ecosystem perspectives
lightbox: TRUE
---

##  {.unnumbered}

For the purpose of synthesizing the information contained in the full suite of indicators presented in this report, we analyze the full indicator suite using multivariate methods. Principal components analysis (PCA) is a statistical method that distills a large number of potentially related indicators into a smaller number of indices representing most of the variability in the data set. We analyze the indicator suite separately by category: 1) risks to meeting management objectives, 2) management objective indicators based on fishery-independent data, 3) management objective indicators based on fishery-dependent data, and 4) other management objective indicators. A traffic light plot of the indicator suite is presented for the purpose of comprehensively viewing changes in the different parts of the ecosystem over time (@fig-traffic). A biplot of the principal components analysis is presented to convey temporal patterns in the progression of ecosystem status (@fig-PCA). PCA was carried out on a scaled matrix for all indicators with at least 12 years of data; any missing values were imputed with means of the time series. In the biplot, the labels represent time (years 2011 – 2023), the rainbow line represents chronology between adjacent years, and the distance between points conveys how different the indicator values were in those years.

![Traffic light plot representing the value of the indicator each year according to quintiles; colors from red to yellow to blue show that the indicator moving between below, at, and above average, respectively (see legend). Indicators are grouped by category, and appear on the plot sorted by their loading (i.e., their influence) from a principal components analysis. In this way, indicators showing similar patterns across time are grouped more closely together.](/indicator_plots/traffic.png){#fig-traffic fig-alt="A plot showing the changes in all indicators over time" fig-align="center" width="40%"}

![Left: Yearly scores of the first two components of a principal components analysis (PCA) for three groups of indicators, based on indicator values from 2011 – 2023. Right: Loadings plots show the relative influence of each indicator in driving the temporal trends observed on the left panel. Loadings with an absolute value greater than 0.2 are considered to be significant.](/indicator_plots/pcas.png){#fig-PCA fig-alt="A plot showing PCA loadings for all indicators" fig-align="center" width="75%"}

Many indicators are based on time series of limited extent or contain data gaps, which makes it challenging to elucidate overall trends. However, the traffic plot conveys that many indicator values undergo rapid change in the period 2017-2021, and the PCA biplots confirm these patterns as there are larger two-dimensional shifts between these years. These shifts are most likely driven by several major stressor events in this time period, including the major hurricanes Maria and Irma (2017) and the COVID pandemic (2020-2021). Together, the multivariate analyses suggest that these events have had some destabilizing impacts on the U.S. Caribbean fishery ecosystem.
