project:
  type: website

website:
  title: "Technical Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Datasets"
        menu:
          - href: issues/Submission_test_submission.qmd
            text: "Test Data 1"
          - href: issues/Submission_Test_data_2.qmd
            text: "Test Data 2"

format:
  html:
    theme: cosmo
